[package]
name = "rewrite"
version = "0.1.0"
edition = "2018"
authors = ["Philip Craig <philipjcraig@gmail.com>"]

[dependencies]
env_logger = "0.5"
object = { path = "../object", features = ["write"] }
gimli = { path = "../gimli" }
memmap = "0.7"
